name: ci-cd

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: "E2E tests"
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install deps
        run: ./npm-install.sh

      - name: install playwright
        run: cd frontend && npx playwright install --with-deps

      - name: fix npm cache permissions
        run: sudo chown -R $(whoami) ~/.npm

      - name: run tests
        run: npx playwright test
        env:
          HOME: /root
          PORT: 4000
          PICT_LOC: ./binaries/pict
          LOG_FILE_PATH: server.log
          VITE_SERVER_BASE_URL: http://localhost:4000

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: html-report/
          retention-days: 7
